# Generated by Django 5.1.5 on 2026-05-05 11:51

from django.db import migrations
from django.utils.text import slugify


CATEGORY_TREE = {
    "Personal Care & Hygiene": [
        "Shampoo",
        "Conditioner",
        "Hair Oil",
        "Hair Serum",
        "Hair Cream",
        "Hair Styling Gel",
        "Hair Wax",
        "Hair Color",
        "Henna",
        "Shampoo Hair Color",
        "Bath Soap",
        "Body Wash",
        "Hand Wash",
        "Hand Sanitizer",
        "Adult Diapers",
        "Body Oil",
    ],
    "Oral Care": ["Toothpaste", "Toothbrush", "Mouthwash"],
    "Skin Care / Creams & Lotion": [
        "Antiseptic Cream",
        "Fairness Cream",
        "Moisturizer",
        "Sunscreen",
        "Face Serum",
        "Men's Cream",
        "Men's Face Wash",
        "Face Wash",
        "Anti Aging Cream",
        "BB Cream",
        "CC Cream",
        "Foundation",
        "Compact",
        "Glycerin",
        "Cold Cream",
        "Face Pack",
        "Face Scrub",
        "Antiseptic Liquids",
    ],
    "Vaseline & Lip Care": ["Petroleum Jelly", "Lip Balm"],
    "Perfume & Fragrance": ["Perfume", "Deodorant", "Pocket Deo", "Roll On"],
    "Razor & Grooming": ["Blades", "Razor", "Shaving Cream", "Shaving Lotion", "Shaving Brush"],
    "Household Essentials": [
        "Toilet Cleaner",
        "Glass Cleaner",
        "Lizol/Floor Cleaner",
        "Bathroom Cleaner",
        "Phenyl",
        "Bleaching Powder",
        "Toilet Brush",
        "Utensil Scrub",
        "Cloth Washing Brush",
        "Floor Brush",
        "Dishwasher Bar",
        "Dishwasher Gel",
        "Clothes Detergent",
        "Naphthalene Balls",
        "Incense Sticks",
        "Candles",
        "Safety Pins",
        "Lighters",
        "Shoe Brush",
        "Shoe Polish",
    ],
    "Utilities": [
        "Batteries",
        "Torch Light",
        "Glue / Gum",
        "Tapes",
        "Scissors",
        "Nail Cutter",
        "Needles & Thread",
        "Nail Remover",
        "Cotton",
        "Combs",
        "Handkerchief",
        "Rope",
        "Lock & Keys",
        "Mirrors",
        "Ear Buds",
        "Bandages",
        "Cloth Clips",
        "Toilet Papers",
        "Bulbs",
        "Drawing Pins",
    ],
    "Games": ["Playing Cards", "Housie Books", "Tennis Balls", "Balloons"],
    "Baby Care": [
        "Baby Soap",
        "Baby Cream",
        "Baby Powder",
        "Baby Oil",
        "Baby Shampoo",
        "Baby Lotion",
        "Baby Hair Oil",
        "Baby Body Wash",
        "Baby Diapers",
        "Baby Wipes",
        "Anti Rash Cream",
        "Baby Bottles",
        "Soother",
        "Teether",
        "Gripe Water",
        "Baby Gift Sets",
    ],
    "Stationery": [
        "Plain Notebook",
        "Ruled Notebook",
        "Gel Pen",
        "Ball Pen",
        "Pencil",
        "Eraser",
        "Sharpener",
        "Lead Pencil",
        "Lead",
        "Marker",
        "Highlighter",
        "Scale",
        "Correction Pen",
        "Scissors",
        "Cellotape",
        "Stapler & Pins",
        "Pocket Diary",
        "Color Pencil",
        "Sketch Pen",
        "Wax Crayons",
        "Plastic Crayons",
        "Water Color",
        "Geometry Box",
        "Book Cover",
        "Chalk",
        "Slate",
        "Exam Board",
        "Glue Stick",
    ],
    "Female Hygiene": ["Sanitary Pads", "Panty Liners", "Veet", "Hair Remover", "Razor"],
}


def seed_category_tree(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    SubCategory = apps.get_model("catalog", "SubCategory")
    Brand = apps.get_model("catalog", "Brand")

    for idx, (name, subcats) in enumerate(CATEGORY_TREE.items(), start=1):
        cat, _ = Category.objects.get_or_create(
            name=name,
            defaults={"slug": slugify(name), "is_active": True, "order": idx},
        )
        updated = False
        if not cat.slug:
            cat.slug = slugify(name)
            updated = True
        if cat.order != idx:
            cat.order = idx
            updated = True
        if not cat.is_active:
            cat.is_active = True
            updated = True
        if updated:
            cat.save()

        for s_idx, sub_name in enumerate(subcats, start=1):
            SubCategory.objects.get_or_create(
                category=cat,
                name=sub_name,
                defaults={"slug": slugify(sub_name), "is_active": True, "order": s_idx},
            )

    # Create common brand placeholders for filters/admin consistency.
    for b in ["Unbranded", "Generic", "Local Brand"]:
        Brand.objects.get_or_create(name=b, defaults={"slug": slugify(b), "is_active": True})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_product_sku_product_brand_obj_productvariant_and_more'),
    ]

    operations = [migrations.RunPython(seed_category_tree, noop_reverse)]
