# Generated by Django 4.2.11 on 2026-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_category_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed bundle savings percentage', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of single items in one packet/bundle', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packet_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual packet/bundle selling price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='single_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of one item if bought separately', max_digits=10, null=True),
        ),
    ]
