# Generated by Django 4.2.11 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_discount_percentage_product_pack_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_quantity_unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('g', 'g'), ('pieces', 'pieces')], help_text='Unit for net quantity', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='net_quantity_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric net quantity for one packet/unit', max_digits=10, null=True),
        ),
    ]
