# Generated by Django 4.2.11 on 2026-05-11 05:33

from django.db import migrations, models
import django.db.models.deletion


def seed_placements(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Placement = apps.get_model("catalog", "ProductPlacement")
    for p in Product.objects.all().iterator():
        Placement.objects.get_or_create(
            product_id=p.pk,
            category_id=p.category_id,
            subcategory_id=p.subcategory_id,
        )


def clear_placements(apps, schema_editor):
    Placement = apps.get_model("catalog", "ProductPlacement")
    Placement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_games_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_placements', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='catalog.product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_placements', to='catalog.subcategory')),
            ],
            options={
                'verbose_name': 'product placement',
                'verbose_name_plural': 'product placements',
            },
        ),
        migrations.RunPython(seed_placements, clear_placements),
        migrations.AddConstraint(
            model_name='productplacement',
            constraint=models.UniqueConstraint(fields=('product', 'category', 'subcategory'), name='catalog_productplacement_unique_cat_sub'),
        ),
    ]
